idlgen/hbs/composite.hbs
idlgen/hbs/idl_ex.hbs
idlgen/hbs/variant.hbs
idlgen/src/lib.rs
idlgen/src/type_names.rs

- Rename `record` -> `struct`
- Change fields separator to `,`
- Add semicolon after function declarations
- Rename `variant` -> `enum`

Change idl format

---

idlgen/src/lib.rs
idlgen/src/type_names.rs

Avoid using the '<' and '>' symbols in type names generated from generics. Use `For' and 'And' instead.
GenericType<T1, u32> -> GenericTypeForT1AndU32

feat(idl-gen): Avoid using '<' and '>' in type names generated from generics

---

idlgen/src/lib.rs
idlgen/src/type_names.rs
idlparser/src/ast/mod.rs
idlparser/src/ast/visitor.rs
idlparser/src/ffi/ast/visitor.rs
idlparser/src/grammar.lalrpop
idlparser/src/lexer.rs

Arrays are supported in form of
`[<item_type>, <len>]`, e.g. `[u8, 10]`
Maps are supported in form of
`map (<key_type>, <value_type>)`, e.g. `map (u32, vec u8)`
Visitor is extended with new methods
`visit_array_type_decl(item_type_decl: &TypeDecl, len: u32)`
`visit_map_type_decl(key_type_decl: &TypeDecl, value_type_decl: &TypeDecl)`

feat(idl-parser, idl-gen): Support fixed size arrays and maps in IDL

---

Cargo.lock
Cargo.toml
client-gen/src/snapshots/sails_clientgen__generator__tests__rmrk_works.snap
examples/rmrk/catalog/app/Cargo.toml
examples/rmrk/catalog/app/src/errors.rs
examples/rmrk/catalog/app/src/lib.rs
examples/rmrk/catalog/app/src/parts.rs
examples/rmrk/catalog/wasm/Cargo.toml
examples/rmrk/catalog/wasm/rmrk-catalog.idl
examples/rmrk/catalog/wasm/src/lib.rs
examples/rmrk/resource/app/Cargo.toml
examples/rmrk/resource/app/src/errors.rs
examples/rmrk/resource/app/src/lib.rs
examples/rmrk/resource/app/src/resources.rs
examples/rmrk/resource/wasm/Cargo.toml
examples/rmrk/resource/wasm/rmrk-resource.idl
examples/rmrk/resource/wasm/src/lib.rs
examples/rmrk/resource/wasm/tests/resources.rs
exec-context/abstractions/Cargo.toml
exec-context/abstractions/src/lib.rs
js/src/generate/types-gen.ts
runtimes/gstd/Cargo.toml
runtimes/gstd/src/lib.rs
runtimes/rtl/Cargo.toml
runtimes/rtl/src/lib.rs
runtimes/rtl/src/prelude.rs
runtimes/rtl/src/types.rs

This is a step towards resolving #85 
The PR introduces build-in types for `ActorId`, `MessageId` and `CodeId` as well as a sort of runtime crates as an analogy of C runtime library.
The `sails-rtl` crate incorporates base primitive types, re-exports for common types and some abstractions which are implemented in a more specific crates.
The `sails-rtl-gstd` crate is basically about re-exporting `gstd` types + implementing abstractions from the `sails-rtl` crate using means provide by `gstd`

feat(runtime): Introduce runtime libraries and some primitive types

---

idlparser/Cargo.toml

The options are:
1. ignored as they are not in the root of the workspace
2. doesn't give any benefit

build(idl-parser): Remove ignored options

---

examples/puppeteer/wasm/src/lib.rs
examples/rmrk/catalog/app/src/lib.rs
examples/rmrk/resource/app/src/lib.rs
examples/this-that-svc/wasm/src/lib.rs
macros/core/src/service.rs
macros/core/src/shared.rs
macros/core/src/snapshots/sails_macros_core__service__tests__gservice_works.snap
macros/core/src/snapshots/sails_macros_core__service__tests__gservice_works_for_lifetimes_and_generics.snap
macros/tests/ui/gservice_works.rs
macros/tests/ui/gservice_works_for_lifecycles_and_generics.rs

This PR refactors generation of dispatching code for service. Instead of generating them as free functions of newly introduced module, we generate them as methods of the service itself. It will help to generate program dispatching code in the scope of #86

refactor(macros): Generate service dispatching code as service methods

---

client-gen/src/generator.rs
client-gen/src/lib.rs
idlparser/src/ast/mod.rs
idlparser/src/ast/visitor.rs
idlparser/src/ffi/ast/mod.rs
idlparser/src/ffi/ast/visitor.rs
idlparser/src/grammar.lalrpop
idlparser/src/lexer.rs
js/src/parser/parser.ts

Resolves #112  .
This PR introduces optional `constructor` block in program IDL. The block can contain possible methods/functions which can be used for constructing a program.
In order to simplify IDL grammar for the time being, IDL structure has been made stricter. It requires specific order of the blocks used:
- any number of `type` blocks
- optional `constructor` block
- required `service` block
Later it can be reconsidered and more flexibility provided

feat(idl-parser): Introduce 'constructor' block

---

macros/core/src/service.rs
macros/core/src/snapshots/sails_macros_core__service__tests__gservice_works.snap
macros/core/src/snapshots/sails_macros_core__service__tests__gservice_works_for_lifetimes_and_generics.snap

Resolves #72  .
Unnecessary memory allocations and runtime route encoding has been removed by this PR.
As it comes to using a hash in lieu of bytes, we might return to this later when we have some means allowing any node event listener like indexer to obtain an IDL for a program of interest and compute hash on its side so it can match responses with a specific methods.

fix(macros): Remove unnecessary memory allocations during service invocation routing

---

idlgen/src/type_names.rs

fix(idl-gen): Fix generic type name generation when reserved types used as params

---

idlparser/src/ast/mod.rs
idlparser/src/ast/visitor.rs
idlparser/src/ffi/ast/mod.rs
idlparser/src/ffi/ast/visitor.rs
idlparser/src/grammar.lalrpop
idlparser/src/lexer.rs
js/src/parser/parser.ts

This PR introduces support for parsing `events` sub-section of the `service` one. The sub-section denotes events possibly emitted by a service. In general, the format of the sub-section matches to `enum` definition, i.e. each `event` line looks exactly the same as `enum variant` one.

feat(idl-parser): Introduce service event parsing

---

examples/rmrk/resource/wasm/rmrk-resource.idl
idl-meta/src/lib.rs
idlgen/hbs/idl.hbs
idlgen/hbs/variant.hbs
idlgen/src/errors.rs
idlgen/src/lib.rs
idlgen/src/meta.rs
idlgen/src/snapshots/sails_idlgen__tests__generare_program_idl_works_with_empty_ctors.snap
idlgen/src/snapshots/sails_idlgen__tests__generare_program_idl_works_with_non_empty_ctors.snap
idlgen/src/snapshots/sails_idlgen__tests__generate_service_idl_works.snap
macros/core/src/service.rs
macros/core/src/snapshots/sails_macros_core__service__tests__gservice_works.snap
macros/core/src/snapshots/sails_macros_core__service__tests__gservice_works_for_lifetimes_and_generics.snap

This PR introduces generation of the `events` section for IDL.
The event type is discovered through the `EventTrigger<EventType>` trait bound used by service.

feat(idl-gen, macro): Implement generation of the events section in idl

---

idlgen/tests/generator.rs
idlparser/src/ast/mod.rs
idlparser/src/ast/visitor.rs
idlparser/src/ffi/ast/mod.rs
idlparser/src/ffi/ast/visitor.rs
idlparser/src/grammar.lalrpop

Some steps towards resolving #87 
This PR introduces support for multiple services in `idl-parser`. Some checks like unique service names are still missing though and will be implemented in a separate PR.

feat(idl-parser): Introduce support for multiple services

---

examples/rmrk/resource/wasm/tests/resources.rs
js/README.md
js/package.json
js/src/generate/service-gen.ts
js/src/index.ts
js/src/sails.ts
js/src/utils/index.ts
js/src/utils/prefix.ts
js/test/rmrk-catalog.test.ts
js/test/rmrk-resource.test.ts
macros/core/src/program.rs
macros/core/tests/snapshots/program__gprogram_generates_handle_for_multiple_services_with_empty_and_non_empty_routes.snap
macros/core/tests/snapshots/program__gprogram_generates_handle_for_multiple_services_with_non_empty_routes.snap
macros/core/tests/snapshots/program__gprogram_generates_handle_for_single_service_with_non_empty_route.snap
macros/core/tests/snapshots/program__gprogram_generates_init_for_multiple_ctors.snap
macros/core/tests/snapshots/program__gprogram_generates_init_for_single_ctor.snap
rtl/src/gstd/events.rs
rtl/src/gstd/mod.rs

Each emitted event payload needs be prefixed with service name/invocation route. Event trigger resolves the latter via a map which is maintained by dispatching code which attributes id of being processed message with the route. The approach requires at least 2 calls to `gstd::msg::id()` which is not that cheap. Current there is no option to cache it somehow.

fix(events): Prefix emitted events with service invocation route

---

Cargo.toml

This PR should resume dependabot PRs for rust based deps

build(deps): Remove wrong/outdated deps from  Cargo.toml

---

examples/puppeteer/wasm/src/lib.rs
examples/this-that-svc/wasm/src/lib.rs
macros/core/src/program.rs
macros/core/src/service.rs
macros/core/tests/snapshots/program__gprogram_generates_handle_for_multiple_services_with_non_empty_routes.snap
macros/core/tests/snapshots/program__gprogram_generates_handle_for_single_service_with_non_empty_route.snap
macros/core/tests/snapshots/service__gservice_works.snap
macros/core/tests/snapshots/service__gservice_works_for_lifetimes_and_generics.snap
macros/tests/ui/gservice_works.rs
macros/tests/ui/gservice_works_for_lifecycles_and_generics.rs
rtl/src/gstd/events.rs
rtl/src/gstd/mod.rs
rtl/src/gstd/services.rs

Resolves #208 .
With this PR service ctor methods used in program adjusted by the `gprogram` macro so they return service exposure instead of service itself

feat(macros): Use exposed service in code generated by 'gprogram' macro

---

rs/client-gen/src/ctor_generators.rs
rs/client-gen/tests/snapshots/generator__full.snap
rs/client-gen/tests/snapshots/generator__rmrk_works.snap

Fix clippy
```
error: field `remoting` is never read
--> E:\git\sails\target\debug\build\rmrk-resource-app-1f62bdc1bf23b6d4\out/rmrk_catalog.rs:11:5
|
10 | pub struct RmrkCatalogFactory<R> {
|            ------------------ field in this struct
11 |     remoting: R,
|     ^^^^^^^^
```

chore: Fix clippy - allow dead_code on field (rust 1.80)

---

Cargo.lock
examples/demo/app/Cargo.toml
examples/demo/app/build.rs
examples/no-svcs-prog/wasm/Cargo.toml
examples/no-svcs-prog/wasm/build.rs
examples/rmrk/catalog/wasm/Cargo.toml
examples/rmrk/catalog/wasm/build.rs
examples/rmrk/resource/wasm/Cargo.toml
examples/rmrk/resource/wasm/build.rs
rs/Cargo.toml
rs/src/lib.rs

Makes the `sails-rs` crate even more self-sufficient

chore: add 'gear-wasm-builder' into 'sails-rs' as an optional dep with re-export

---

js/compress-parser.js
js/src/parser/parser.ts

Resolves #453 .
-
-
-
@reviewer-or-team

fix(js): don't use the spread operator to append to a large array

---

rs/idl-gen/src/lib.rs

feat(idl-gen): allow non-existing dirs in path for 'generate_idl_to_file'

---

rs/cli/src/main.rs
rs/cli/src/program.rs

- `--with-client` and `--with-gtest` are replaced by `--no-client` and `--no-gtest` respectively
- `cargo-cli` passes its version to template generation engine. The upcoming template version will check for compatibility.

feat(cli): invert params of 'new-program' in 'cargo-sails'

---

rs/README.md
rs/src/lib.rs

This is required to allow building a package for crates-io. `cargo-package` moves the entire crate content into the `target\package` directory ignoring all the files outside of the original crate directory making some relative pathes broken. Currently the solution works on Unix-based systems only. For Win, it will probably require creating a win symlink (`mklink`) and use it via conditional compilation

build: add readme to 'sails-rs' as a symlink for proper packaging

---

templates/cargo-generate.toml
templates/program-alt/Cargo.toml
templates/program-alt/build.rs
templates/program-alt/client/Cargo.toml
templates/program-alt/client/build.rs
templates/program-alt/client/src/lib.rs
templates/program-alt/src/lib.rs
templates/program-alt/tests/gtest.rs
templates/program/Cargo.toml
templates/program/README.md
templates/program/app/Cargo.toml
templates/program/app/src/lib.rs
templates/program/build.rs
templates/program/src/lib.rs
templates/set-vars.rhai

The new template generates 2 separate packages in its base variant:
- one for for business logic
- one for for building wasm

feat(template): generate program worspace using separate packages for app and wasm

---

rs/macros/core/src/service/mod.rs
rs/macros/core/tests/gservice.rs
rs/macros/core/tests/snapshots/gservice__works_with_allow_attrs.snap

Resolves #526  .
We do propagate only the `allow` attr at the moment as there might be args which can lead to undesired outcome

feat(macros): propagate allow attrs for service impls and fns

---

rs/src/gclient/calls.rs

Add `QueryAtBlock` trait with impl only for `Query<Args = GClientArgs>`
Usage
```
client.query().at_block({hash}).recv(program_id).await;
```

feat(gclient): impl `at_block` for query at specific block

---

.github/workflows/rs-ci.yml
.github/workflows/rs-release.yml
Cargo.lock
Cargo.toml

Resolves version conflict because of 3.6.12's bound to derive ">=3.6.12" instead of hard pin.

build(deps): bump parity-scale-codec from 3.6.12 to 3.7.4

---

.github/workflows/rs-ci.yml
.github/workflows/rs-run-cli-tests.yml
.github/workflows/rs-run-ws-tests.yml

Resolves wabt CI build
NOTE: remove after bump Gear version https://github.com/gear-tech/gear/pull/4494

fix(build): CI wabt-sys build error `Compatibility with CMake < 3.5 has been removed from CMake.`
