- examples/rmrk/resource/app/src/lib.rs
> build(fix): Fix build after intorducing minifyied name generation

- examples/rmrk/resource/app/src/lib.rs
> build(fix): Fix build after introducing builtin types

- Cargo.lock
- Cargo.toml
- examples/rmrk/resource/app/src/services/mod.rs
- examples/rmrk/resource/wasm/Cargo.toml
- examples/rmrk/resource/wasm/tests/resources.rs
- rtl/Cargo.toml
- rtl/src/calls.rs
- rtl/src/errors.rs
- rtl/src/gstd/mod.rs
- rtl/src/gtest/calls.rs
- rtl/src/gtest/mod.rs
- rtl/src/lib.rs
- rtl/src/types.rs
Changes towrds resolving #94 
At the moment the code lacks of activation functionality due to missing such in `gtest` itself
> feat(rtl): Introduce implementation of Remoting for GTest

- .github/workflows/ci.yml
- macros/tests/integration_tests.rs
- macros/tests/ui/gprogram_fails_for_multiple_services_with_same_route.rs
- macros/tests/ui/gprogram_fails_for_multiple_services_with_same_route.stderr
> tests(macros): Test multiple services with same route lead to compilation error

- examples/rmrk/catalog/wasm/rmrk-catalog.idl
- examples/rmrk/resource/wasm/rmrk-resource.idl
- examples/this-that-svc/wasm/this-that-svc.idl
- idlgen/hbs/idl.hbs
- idlgen/src/lib.rs
- idlgen/src/meta.rs
- idlgen/tests/generator.rs
- idlgen/tests/snapshots/generator__generare_program_idl_works_with_non_empty_ctors.snap
- idlgen/tests/snapshots/generator__generate_program_idl_works_with_multiple_services.snap
- idlgen/tests/snapshots/generator__generate_service_idl_works.snap
Resolves #87.
This is final PR for supporting multiple services
> feat(idl-gen): Support multiple services

- examples/rmrk/catalog/app/src/services/mod.rs
- examples/rmrk/resource/app/src/services/mod.rs
- rtl/src/gstd/mod.rs
- rtl/src/lib.rs
Resolves #185
we also need to discuss #181
> feat: Pass copyable types by value

- client-gen/src/lib.rs
- examples/puppeteer/app/build.rs
- examples/rmrk/resource/app/build.rs
> fix(client-gen): Pass paths with AsRef<Path>

- Cargo.lock
- Cargo.toml
- client-gen/src/generator.rs
- examples/this-that-svc/app/Cargo.toml
- examples/this-that-svc/app/src/lib.rs
- examples/this-that-svc/wasm/this-that-svc.idl
- idlgen/src/meta.rs
- idlgen/src/type_names.rs
- idlgen/tests/generator.rs
- idlgen/tests/snapshots/generator__generare_program_idl_works_with_empty_ctors.snap
- idlgen/tests/snapshots/generator__generare_program_idl_works_with_non_empty_ctors.snap
- idlgen/tests/snapshots/generator__generate_program_idl_works_with_multiple_services.snap
- idlgen/tests/snapshots/generator__generate_service_idl_works.snap
- idlparser/src/ast/mod.rs
- rtl/Cargo.toml
- rtl/src/types.rs
> feat(idl): Support H256, U256 from the primitive-types crate as builtins

- examples/rmrk/resource/wasm/tests/resources.rs
- rtl/src/errors.rs
- rtl/src/gtest/calls.rs
Resolves #94 .
Missing implementation of program spinning up added.
> feat(rtl): Complete implementation of program space for GTest

- macros/core/src/program.rs
- macros/core/src/route.rs
- macros/core/src/shared.rs
- macros/core/tests/program.rs
- macros/tests/integration_tests.rs
- macros/tests/ui/gprogram_fails_for_multiple_services_with_same_route.stderr
- macros/tests/ui/gprogram_fails_for_service_with_empty_route.rs
- macros/tests/ui/gprogram_fails_for_service_with_empty_route.stderr
> feat(macros): Forbid anonymously exposed services

- Cargo.lock
- idlparser/Cargo.toml
- idlparser/src/ast/mod.rs
- idlparser/src/ast/visitor.rs
- idlparser/src/grammar.lalrpop
- idlparser/src/lexer.rs
* make constructors uphold the contract that the types are sane
* introduce ParseError type
Resolves #170
Resolves #169
Resolves #168
Resolves #167
> feat(idlparser): Add a bunch of IDL checks

- macros/core/src/program.rs
- macros/core/tests/snapshots/program__gprogram_generates_init_for_multiple_ctors.snap
- macros/core/tests/snapshots/program__gprogram_generates_init_for_single_ctor.snap
- macros/tests/integration_tests.rs
- macros/tests/ui/gprogram_works.rs
Resolves https://github.com/gear-tech/sails/issues/183 .
> fix(macros): rustc complains about unused fields in __NewParams, allow dead_code on generated struct

- rtl/src/gstd/events.rs
- rtl/src/gstd/mod.rs
Added Clone to places where it (hopefully) makes sense.
Resolves #266
> feat(rtl): Add derive(Clone) to several things

- examples/rmrk/resource/app/src/lib.rs
- examples/rmrk/resource/app/src/services/mod.rs
- macros/core/src/service.rs
- macros/core/tests/gservice.rs
- macros/core/tests/snapshots/gservice__works_with_lifetimes_and_generics.snap
- rtl/src/gstd/events.rs
- rtl/src/gstd/mod.rs
- rtl/src/prelude.rs
> refactor(rtl): Rename EventTrigger into EventNotifier and document it

- client-gen/src/ctor_generators.rs
- client-gen/src/service_generators.rs
- client-gen/tests/snapshots/generator__basic_works.snap
- client-gen/tests/snapshots/generator__full.snap
- client-gen/tests/snapshots/generator__multiple_services.snap
- client-gen/tests/snapshots/generator__rmrk_works.snap
- examples/puppeteer/app/src/lib.rs
- examples/puppeteer/wasm/src/lib.rs
- examples/rmrk/resource/app/src/services/mod.rs
> feat(client-gen): Move remoting into ctor impl

- client-gen/src/io_generators.rs
- client-gen/tests/snapshots/generator__multiple_services.snap
- client-gen/tests/snapshots/generator__rmrk_works.snap
> fix(client-gen): Add path validation in decode_reply

- Makefile
- js/src/generate/service-gen.ts
- js/src/index.ts
- js/src/sails.ts
- js/src/transaction-builder.ts
- js/test/this-that.test.ts
> fix(js): bugs

- README.md
- examples/demo/app/src/counter/README.md
- examples/demo/app/src/counter/mod.rs
- examples/demo/app/src/lib.rs
- examples/demo/app/src/ping/README.md
- examples/demo/app/src/ping/mod.rs
- examples/demo/app/src/references/README.md
- examples/demo/app/src/this_that/README.md
- examples/demo/app/src/this_that/mod.rs
- examples/demo/wasm/src/lib.rs
- examples/rmrk/catalog/app/src/services/mod.rs
- examples/rmrk/catalog/wasm/src/lib.rs
- examples/rmrk/resource/app/src/services/mod.rs
- examples/rmrk/resource/wasm/src/lib.rs
> docs: Add some examples descriptions

- README.md
- examples/rmrk/resource/app/src/services/mod.rs
> docs: Add some explanation wrt statics and async

- README.md
- examples/demo/client/build.rs
- examples/demo/client/src/README.md
- examples/demo/client/src/lib.rs
- examples/demo/wasm/tests/fixture/mod.rs
- examples/demo/wasm/tests/gclient.rs
- examples/demo/wasm/tests/gtest.rs
- examples/rmrk/resource/app/src/services/mod.rs
Final part toward #316. Resolves #316 .
> docs, examples: Elaborate on generated clients

- .github/workflows/ci.yml
- Makefile
- examples/demo/wasm/build.rs
- examples/no-svcs-prog/wasm/build.rs
- examples/proxy/wasm/build.rs
- examples/rmrk/catalog/wasm/build.rs
- examples/rmrk/resource/wasm/build.rs
- sails/idl-gen/src/errors.rs
- sails/idl-gen/src/lib.rs
This PR improves IDL build UX. It introduces a new function allowing to generate IDL to the specified path with a check whether IDL file overwritting is actually required.
Also, it disables feature tracking check during WASM build in hope it will minimize build time
> build: Improve IDL build UX

- examples/demo/wasm/tests/fixture/mod.rs
- examples/demo/wasm/tests/gtest.rs
- examples/rmrk/resource/wasm/tests/resources.rs
- sails/src/errors.rs
- sails/src/gtest/calls.rs
> chore(sails): Add default ActorId to GTestRemoting

- rs/macros/core/src/program/mod.rs
- rs/macros/core/src/service/mod.rs
- rs/macros/core/tests/snapshots/gprogram__generates_handle_for_multiple_services_with_non_empty_routes.snap
- rs/macros/core/tests/snapshots/gprogram__generates_handle_for_single_service_with_non_empty_route.snap
- rs/macros/core/tests/snapshots/gprogram__generates_handle_with_gprogram_attributes.snap
- rs/macros/core/tests/snapshots/gprogram__generates_init_for_multiple_ctors.snap
- rs/macros/core/tests/snapshots/gprogram__generates_init_for_no_ctor.snap
- rs/macros/core/tests/snapshots/gprogram__generates_init_for_single_ctor.snap
- rs/macros/core/tests/snapshots/gservice__works_with_basics.snap
- rs/macros/core/tests/snapshots/gservice__works_with_events.snap
- rs/macros/core/tests/snapshots/gservice__works_with_extends.snap
- rs/macros/core/tests/snapshots/gservice__works_with_extends_and_lifetimes.snap
- rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_events.snap
- rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_generics.snap
Resolves #399  .
-
-
-
@reviewer-or-team
> fix:defined meta multiple

- Cargo.lock
- README.md
- examples/no-svcs-prog/wasm/Cargo.toml
- examples/no-svcs-prog/wasm/no-svcs-prog.idl
- examples/no-svcs-prog/wasm/src/client.rs
- examples/no-svcs-prog/wasm/tests/tests.rs
- rs/macros/core/src/program/mod.rs
- rs/macros/core/src/service/mod.rs
- rs/macros/core/src/shared.rs
- rs/macros/core/tests/snapshots/gprogram__generates_handle_for_multiple_services_with_non_empty_routes.snap
- rs/macros/core/tests/snapshots/gprogram__generates_handle_for_single_service_with_non_empty_route.snap
- rs/macros/core/tests/snapshots/gprogram__generates_handle_with_gprogram_attributes.snap
- rs/macros/core/tests/snapshots/gprogram__generates_init_for_no_ctor.snap
Resolves #344.
Generate default program ctor if there are no user-defined ones discovered
> feat(macros): generate program default ctor if there are no user-defined ones

- examples/demo/app/tests/gclient.rs
- examples/rmrk/resource/wasm/tests/resources.rs
- rs/src/calls.rs
- rs/src/gsdk/calls.rs
- rs/src/gstd/calls.rs
- rs/src/gtest/calls.rs
- rs/src/mockall.rs
GTest calls with gas_limit in PR https://github.com/gear-tech/sails/pull/439
Part of #436 .
> feat(sails-rs): Introduce common support for 'with_gas_limit' option in the 'Action' trait

- rs/Cargo.toml
> build: introduce 'debug' feature in 'sails-rs' crate

- Cargo.lock
- examples/demo/app/Cargo.toml
- examples/demo/app/src/this_that/mod.rs
- examples/rmrk/resource/app/Cargo.toml
- rs/src/gstd/mod.rs
> chore: re-export 'gstd::debug' macro from 'sails-rs'

- rs/macros/core/src/program/mod.rs
> fix(macros): Ensure single `program` proc_macro attribute per crate

- examples/rmrk/resource/app/src/services/mod.rs
- rs/src/gsdk/calls.rs
- rs/src/gstd/calls.rs
- rs/src/gtest/calls.rs
> feat(sails, gstd): Support for handle_reply in gstd MessageFuture

- rs/src/gstd/events.rs
> fix(sails-rs): Rare error in sails-rs gstd::events::tests

- templates/program/client/Cargo.toml
- templates/program/client/build.rs
- templates/program/client/src/lib.rs
- templates/program/src/lib.rs
- templates/program/tests/gtest.rs
- templates/set-vars.rhai
This PR completes program generation from template by adding fully featured client and tests
> feat(template): add client and tests to the program template

- js/src/transaction-builder.ts
- withGas
- withValue
Resolves #451  .
-
-
-
@reviewer-or-team
> feat(js): Make some async methods on TransactionBuilder sync

- Cargo.lock
- Cargo.toml
- examples/demo/app/Cargo.toml
- examples/no-svcs-prog/app/src/lib.rs
- examples/no-svcs-prog/wasm/Cargo.toml
- examples/rmrk/catalog/app/Cargo.toml
- examples/rmrk/catalog/app/src/lib.rs
- examples/rmrk/catalog/app/src/services/errors.rs
- examples/rmrk/catalog/app/src/services/parts.rs
- examples/rmrk/resource/wasm/Cargo.toml
- rs/Cargo.toml
- rs/src/errors.rs
- rs/src/lib.rs
- rs/src/prelude.rs
- rs/src/types.rs
> feat: introduce feature flags 'gstd', 'gtest', 'gclient' for 'sails-rs'

- rs/cli/src/main.rs
- templates/cargo-generate.toml
- templates/check-version.rhai
- templates/pre-hook.rhai
- templates/program/Cargo.toml
- templates/set-vars.rhai
Support cli options in template + use sails 0.4.0 with features
> feat(cli): support '--no-client' and '--no-gtest' flags in 'cargo-sails' template

- .github/workflows/ci.yml
- rs/cli/src/main.rs
- rs/src/errors.rs
> fix: 'cargo-sails' commands structure for being a proper cargo extension

- rs/idl-gen/src/type_names.rs
- rs/idl-gen/tests/generator.rs
- rs/idl-gen/tests/snapshots/generator__program_idl_works_with_empty_ctors.snap
- rs/idl-gen/tests/snapshots/generator__program_idl_works_with_multiple_services.snap
- rs/idl-gen/tests/snapshots/generator__program_idl_works_with_non_empty_ctors.snap
- rs/idl-gen/tests/snapshots/generator__service_idl_works_with_base_services.snap
- rs/idl-gen/tests/snapshots/generator__service_idl_works_with_basics.snap
> fix(idl-gen): Types with const generics produce invalid IDL

- rs/macros/core/src/program/mod.rs
- rs/macros/core/src/service/mod.rs
- rs/macros/core/src/shared.rs
- rs/macros/tests/gservice_tests.rs
- rs/macros/tests/gservice_with_trait_bounds/mod.rs
> fix(macros): support inline trait bounds

- js/cli/src/generate/format.ts
- js/cli/src/generate/output.ts
- js/cli/src/generate/service-gen.ts
- js/cli/src/generate/types-gen.ts
> feat(js/cli) add support docs

- rs/idl-parser/src/ffi/ast/mod.rs
Fixes compilation on linux arm
> fix(ffi): unify c_char ptr cast

- README.md
Resolves # .
-
-
-
@reviewer-or-team
> doc: cargo sails new-program subcommand renamed to program

- examples/demo/app/src/counter/mod.rs
- rs/macros/core/src/service/mod.rs
- rs/macros/core/src/shared.rs
- rs/macros/core/tests/gservice.rs
- rs/macros/core/tests/snapshots/gservice__works_with_special_lifetimes_and_events.snap
- rs/macros/tests/gservice_tests.rs
- rs/macros/tests/gservice_with_extends_and_lifetimes/mod.rs
- rs/macros/tests/gservice_with_lifecycles_and_generics/mod.rs
- rs/macros/tests/gservice_with_lifetimes_and_events/mod.rs
- rs/macros/tests/gservice_with_trait_bounds/mod.rs
> fix(macors): support special lifetime '_ in service impl

- rs/cli/src/main.rs
- rs/cli/src/program.rs
- templates/check-version.rhai
> [rs]feat(cli): introduce '--sails-version' option for 'cargo sails program'

- js/src/transaction-builder.ts
- js/test/demo.test.ts
Resolves #474 .
- add ability to get GasInfo after gas calculation
- add tests for gas info
@osipov-mit
> feat(js) add ability to get GasInfo after gas calculation

- examples/demo/app/tests/gtest.rs
- rs/src/gtest/calls.rs
Resolves #754  .
`BlockRunMode::Auto` - Run blocks automatically until all pending replies are received.
`BlockRunMode::Next` - Run only next block and exract events and replies from it. If there is no reply in this block then `RtlError::ReplyIsMissing` error will be returned.
`BlockRunMode::Manual` - Use `GTestRemoting::run_next_block` method to run the next block and extract events and replies.
> feat(gtest): gtest run blocks `auto` and `next` mode

- Cargo.lock
- Cargo.toml
- rs/macros/core/src/shared.rs
> build: Update to rust 1.86

- rs/ethexe/ethapp/tests/gtest.rs
- rs/ethexe/ethapp_with_events/tests/gtest.rs
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_ctors_meta_with_docs.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_multiple_services_with_non_empty_routes.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_services_with_unwrap_result.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_for_single_service_with_non_empty_route.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_with_crate_path.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_with_gprogram_attributes.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_for_multiple_ctors.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_for_no_ctor.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_for_single_ctor.snap
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_init_with_unwrap_result.snap
- rs/macros/core/src/program/ethexe.rs
- rs/src/solidity.rs
> feat(ethexe): add encode_reply as second parameter for constructors

- examples/demo/app/src/counter/mod.rs
- examples/demo/app/src/dog/mod.rs
- examples/demo/app/src/value_fee/mod.rs
- examples/demo/walker/src/lib.rs
- examples/rmrk/resource/app/src/services/mod.rs
- rs/ethexe/ethapp_with_events/src/lib.rs
- rs/ethexe/ethapp_with_events/tests/gtest.rs
- rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_events.snap
- rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_lifetimes_and_events.snap
- rs/ethexe/macros-tests/tests/snapshots/service_insta__works_with_special_lifetimes_and_events.snap
- rs/macros/core/src/service/ethexe.rs
- rs/macros/core/src/service/exposure.rs
- rs/macros/core/src/service/mod.rs
- rs/macros/core/tests/snapshots/gservice__works_with_events.snap
- rs/macros/core/tests/snapshots/gservice__works_with_lifetimes_and_events.snap
- rs/macros/core/tests/snapshots/gservice__works_with_special_lifetimes_and_events.snap
- rs/macros/src/lib.rs
- rs/macros/tests/gservice_with_events/mod.rs
- rs/macros/tests/gservice_with_lifetimes_and_events/mod.rs
- rs/src/gstd/events.rs
- rs/src/gstd/mod.rs
> BREAKING CHANGE: rename `notify_on` fn to `emit_event`, add `emit_event` fn to Exposure

- rs/ethexe/macros-tests/tests/program_insta.rs
- rs/ethexe/macros-tests/tests/snapshots/program_insta__generates_handle_with_gprogram_attributes.snap
- rs/macros/core/src/program/args.rs
- rs/macros/core/src/program/mod.rs
- rs/macros/core/tests/gprogram.rs
- rs/macros/core/tests/snapshots/gprogram__generates_async_main_with_handle_reply.snap
- rs/macros/src/lib.rs
- rs/macros/tests/ui/gprogram_fails_handle_reply_signature.rs
- rs/macros/tests/ui/gprogram_fails_handle_reply_signature.stderr
- rs/macros/tests/ui/gprogram_fails_multiple_handle_reply.rs
- rs/macros/tests/ui/gprogram_fails_multiple_handle_reply.stderr
- rs/macros/tests/ui/gprogram_fails_unknown_args.stderr
> chore(macros): add `handle_reply` fn to program impl, remove from `program` attr

- rs/macros/src/lib.rs
- rs/src/gstd/ethexe.rs
- rs/src/gstd/events.rs
- rs/src/gstd/mod.rs
- rs/src/gstd/utils.rs
> feat(sails-rs): Use stack buffer to optimize events encoding

- examples/demo/app/tests/gclient.rs
- rs/src/gclient/calls.rs
> feat(client): support to send a message for query with gclient

- Cargo.lock
- Cargo.toml
- rs/Cargo.toml
- rs/ethexe/Cargo.lock
- rs/src/gstd/syscalls.rs
- rs/src/prelude.rs
> feat: extend Syscalls with reply and signal details getters

- examples/demo/app/src/lib.rs
- examples/demo/app/tests/fixture/mod.rs
- examples/rmrk/resource/wasm/tests/resources.rs
- rs/cli/src/idlgen.rs
- rs/idl-gen/src/lib.rs
- rs/idl-parser/build.rs
- rs/macros/core/src/export/args.rs
- rs/macros/core/src/program/args.rs
- rs/macros/core/src/program/mod.rs
- rs/macros/core/src/shared.rs
- rs/src/gtest/calls.rs
> build: fix rust 1.89.0

- examples/demo/app/src/counter/mod.rs
- examples/demo/app/tests/gclient.rs
- examples/demo/app/tests/gtest.rs
- examples/demo/client/demo_client.idl
- examples/demo/client/src/demo_client.rs
- rs/src/gclient/calls.rs
- rs/src/gtest/calls.rs
> refactor: use `gtest::System::calculate_reply_for_handle` for queries

- js/README.md
- js/src/transaction-builder.ts
> feat(js): expose payload decoding methods from `TransactionBuilder`
